CREATE DATABASE CustomerDB;

USE CustomerDB;
Go
CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50)NOT NULL,
    Address NVARCHAR(100)NOT NULL,
    Phone NVARCHAR(20)NOT NULL
);